name: iPad Pro 11 E2E Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  iPad-Pro-11-e2e-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - run: |
          touch .env
          echo "NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}" >> .env
          echo "PERSONAL_ACCESS_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}" >> .env
      - name: Build Next
        run: pnpm build
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Set build name
        run: echo "BUILD_NAME=iPad Pro 11" >> .env
      - name: Playwright tests
        run: pnpm exec playwright test --project='iPad Pro 11'
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Upload screenshots to Argos
        run: pnpm argos upload ./screenshots
